name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'

    - name: Install Firebase Emulator
      run: yarn global add firebase-tools

    - name: Install dependencies
      run: yarn install

    - name: Run lint
      run: yarn lint

    - name: Run prettier
      run: yarn prettier

    - name: Run back unit tests
      run: yarn test:back:unit

    - name: Run back integration tests
      run: yarn test:back:integration

    - name: Run front tests
      run: yarn test:front

    - name: Build
      run: yarn build

    - name: Run end to end tests
      run: yarn e2e:headless
